# Generated by Django 3.0.8 on 2020-09-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('w_ans1', models.CharField(max_length=280, verbose_name='Worng Answer 1')),
                ('w_ans2', models.CharField(max_length=280, verbose_name='Worng Answer 2')),
                ('w_ans3', models.CharField(max_length=280, verbose_name='Worng Answer 3')),
                ('w_ans4', models.CharField(max_length=280, verbose_name='Worng Answer 4')),
                ('ans', models.CharField(max_length=280, verbose_name='Answer')),
            ],
        ),
    ]
