# Generated by Django 3.0.8 on 2020-09-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='w_ans1',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='w_ans2',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='w_ans3',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='w_ans4',
            new_name='option4',
        ),
    ]
