# Generated by Django 3.0 on 2022-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerform',
            name='exam_status',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='right',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='score',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='total',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='worng',
        ),
        migrations.RemoveField(
            model_name='signupform',
            name='confirm_pwd',
        ),
        migrations.AddField(
            model_name='signupform',
            name='exam_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signupform',
            name='right',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signupform',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signupform',
            name='tot_que',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signupform',
            name='wrong',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
