# Generated by Django 3.1.1 on 2020-09-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_registerform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='registerform',
            name='password2',
        ),
    ]
