# Generated by Django 3.1.1 on 2020-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200916_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='question',
            name='right',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='worng',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
