# Generated by Django 3.0 on 2022-04-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_question_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categoryName',
        ),
        migrations.RemoveField(
            model_name='question',
            name='owner',
        ),
    ]
