# Generated by Django 3.1.1 on 2020-09-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200917_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='right',
        ),
        migrations.RemoveField(
            model_name='question',
            name='worng',
        ),
        migrations.AddField(
            model_name='registerform',
            name='marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='registerform',
            name='right',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registerform',
            name='worng',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
