# Generated by Django 3.0 on 2022-04-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220403_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='categoryName',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.signupform'),
        ),
    ]
