# Generated by Django 3.1.1 on 2020-09-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_registerform_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(blank=True, default='', max_length=280, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='Worng Answer 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='Worng Answer 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='Worng Answer 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='Worng Answer 4'),
        ),
    ]
