# Generated by Django 3.1.1 on 2020-09-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200917_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='exam_status',
            field=models.BooleanField(default=False),
        ),
    ]
