# Generated by Django 3.1.1 on 2020-09-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_registerform_exam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerform',
            name='exam_status',
        ),
    ]
