# Generated by Django 3.2.9 on 2022-03-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_registerform_exam_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('confirm_pwd', models.CharField(max_length=100)),
            ],
        ),
    ]
