# Generated by Django 3.0 on 2022-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_signupform'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='exam_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registerform',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
